version: 2
updates:
- package-ecosystem: bundler
  directory: "/omnibus"
  schedule:
    interval: daily
    time: "08:00"
    timezone: America/New_York
  open-pull-requests-limit: 10
  labels:
  - "Type: Chore"
  ignore:
  - dependency-name: aws*
    versions:
    - ">= 0"
  - dependency-name: test-kitchen
    versions:
    - 2.10.0
    - 2.11.0
    - 2.11.1
